### PR TITLE
Docs Redesign

### PR DESCRIPTION
**Pull request by Mfigueira**
Update all Docs structure and styles with new design

- Add new `Layout` with left menu drawer, simplified header and footer
- Add Hero component, configurable with `frontMatter`
- Add new navigation system, with `NavigationSection`s and `NavigationCardLink`s for main/index pages
- Add new `prev` and `next` articles navigation
- Add `title`, `description`, `readTime`, and `readType` `_meta.json` info to docs pages that will be displayed in the navigation cards (ToDo: add more of these to all relevant pages)
- Add a variety of new icons and illustrations
- Add new main pages with updated components and content (`Home`, `About`, `Support`, `Community`)
- Restructure some docs directories to align better with new designs
- Add new responsive styles for all screen widths
- Fix minor issues and nits from Nextra migration
- Add custom rendered components for mdx content and new Article template layout

### CODE REVIEW

**Comment by fadeev** [comment]
https://github.com/zeta-chain/docs/assets/332151/e02c4c65-e536-4642-b4d8-fcb19c6a0783

Small visual bug when pressing the back button, it flashes the middle of the page you're viewing before actually going back.

**Comment by fadeev** [comment]
Screenshot 2024-05-30 at 10 35 00

@Mfigueira we currently have descriptions in two different places (meta.json and frontmatter). Any chance we can avoid this duplication?

**Comment by fadeev** [comment]
Screenshot 2024-05-30 at 11 12 55

Description should probably be the same with as content.

**Comment by fadeev** [comment]
Quick request: can we, please, make tables left-aligned.

**Comment by fadeev** [comment]
https://github.com/zeta-chain/docs/assets/332151/a06dda0b-35b4-42bc-874e-7c998348ec0c

**Review by lucas-janon — APPROVED** [review]
Looking great 💪

**Review by GMaiolo — APPROVED** [review]
Concept ACK
🚀

**Comment by fadeev** [comment]
When clicking on "Continue Learning" box it doesn't scroll to the top of the page.

**Comment by fadeev** [comment]
The TOC sidebar on the right no longer works.

**Comment by fadeev** [comment]
Screenshot 2024-06-08 at 12 39 02

I've noticed that this components intelligently fetches the nested pages, but one thing it skips is index pages. Which I thought was a small bug, but then I realized we could keep it as a feature and call pages index when we want to skip them and name them differently when we want them bubble up to the top.

**Pull request merged**
