### PR TITLE
create state-sync documentation

### PR DESCRIPTION
**Pull request by julianrubino**
Create documentation with instructions of how to run a RPC node locally and sync it using state-sync.

This procedure was tested and it's working fine.

### CODE REVIEW

**Comment by julianrubino** [comment]
ci

**Review by CharlieMc0 — APPROVED** [review]

**Comment by julianrubino** [comment]
CI

**Comment by fadeev** [comment]
@julianrubino @CharlieMc0 would it be ok if I moved the state sync docs in the "Validators" category? It's an important doc, but its primary audience are validators and node operators, not all developers.

**Comment by julianrubino** [comment]
> @julianrubino @CharlieMc0 would it be ok if I moved the state sync docs in the "Validators" category? It's an important doc, but its primary audience are validators and node operators, not all developers.

@fadeev Yes, we can. We thought of organizing like this because state-sync has nothing to do with validators. Should I move it there anyways? I compared with most of other blockchains docs and they have it like this

**Comment by fadeev** [comment]
@julianrubino not sure I agree that state-sync has nothing to do with validators. Validators run nodes, and state-sync is the main mechanism to bring your node online.

I do agree that "running a node" (for which state-sync is relevant) is a broader term than "validators", but I think anyone who is interested in running a node will easily recognize "Validators" as the category they broadly fall into. So, yes, I think we should move state-sync into "Validators" and reserve space in the top-level navigation for future use.

**Comment by fadeev** [comment]
Screenshot 2023-12-06 at 11 10 18

Screenshot 2023-12-06 at 11 10 31

**Review by fadeev — APPROVED** [review]

**Comment by julianrubino** [comment]
CI

**Comment by julianrubino** [comment]
ci

**Pull request merged**
